app/Http/routes.php
Route::get('/property/showdoc/{docid}', 'PropertyController@showdoc');
Route::get('/property/removedoc/{docid}/{propertyid}', 'PropertyController@removedoc');
Route::get('/property/{property}/{group}/{type}/', 'PropertyMediaController@api_index');
//Route::get('/property/zipimages/{id}', 'PropertyController@zipimages');
Route::get('/property/tobedeleted', 'PropertyController@deleted');
Route::post('/property/delete/confirm', 'PropertyController@confirm_delete');
Route::post('/property/delete/decline', 'PropertyController@decline_delete');
Route::get('/property/deletedproperties', 'PropertyController@deletedproperties');
Route::post('/property/restoreproperty', 'PropertyController@restore_property');
Route::get('/property/property_exists', 'PropertyController@property_exists');
Route::get('/property/property_exists_update', 'PropertyController@property_exists_update');


Route::get('/api/properties/', 'ApiPropertyController@index');
Route::get('/api/property/{property}', 'ApiPropertyController@show');
Route::get('/api/propertyquick/{property}', 'ApiPropertyController@showquick');
Route::get('/api/sitemap/', 'ApiPropertyController@sitemap');
Route::get('/api/full/', 'ApiPropertyController@full');
Route::get('/api/fullext/', 'ApiPropertyController@fullext');
Route::get('/api/propertiesquerycount/', 'ApiPropertyController@PropertyResultsCounter');

Route::get('/buildings/api/index', 'BuildingController@api_index');
Route::get('/buildings', 'BuildingController@index');
Route::get('/building/create', 'BuildingController@create');
Route::get('/building/show/{property}', 'BuildingController@show');
Route::get('/building/edit/{building}', 'BuildingController@edit');
Route::post('/building/store', 'BuildingController@store');
Route::post('/building/update', 'BuildingController@update');
Route::post('/building/remove', 'BuildingController@remove');
Route::post('/building/updatenames', 'BuildingController@updatenames');
Route::post('/building/updateaddress', 'BuildingController@updateaddress');
Route::post('/building/updatefacilities', 'BuildingController@updatefacilities');
Route::delete('/building/{building}', 'BuildingController@destroy');
Route::get('/building/geoapitest', 'BuildingController@geoapitest');

Route::get('/districts', 'DistrictController@index');
Route::any('/districts/option/reorder', 'DistrictController@option_reorder');
Route::any('/districts/select', 'DistrictController@frontend_select');
Route::any('/districts/export', 'DistrictController@frontend_export');

Route::get('/vendors/api/{type}/index', 'VendorController@api_index');
Route::get('/vendors/api/child/{parent_id}', 'VendorController@api_child_index');
Route::get('/vendors', 'VendorController@index');
Route::get('/vendor/create', 'VendorController@create');
Route::get('/vendor/show/{property}', 'VendorController@show');
Route::get('/vendor/edit/{vendor}', 'VendorController@edit');
Route::post('/vendor/store', 'VendorController@store');
Route::post('/vendor/update', 'VendorController@update');
Route::post('/vendor/remove', 'VendorController@remove');
Route::delete('/vendor/{vendor}', 'VendorController@destroy');
Route::get('/vendor/create-rep/{owner}', 'VendorController@create_rep');
Route::get('/vendor/create-agent/{agent}', 'VendorController@create_agent');
Route::get('/vendor/phonesearch/{phone}', 'VendorController@phonesearch');

Route::get('/clients', 'ClientController@index');
Route::get('/client/create', 'ClientController@create');
Route::get('/client/show/{property}', 'ClientController@show');
Route::get('/client/edit/{client}', 'ClientController@edit');
Route::post('/client/store', 'ClientController@store');
Route::post('/client/api/store', 'ClientController@api_store');
Route::post('/client/update', 'ClientController@update');
Route::delete('/client/{client}', 'ClientController@destroy');
Route::post('/client/docupload/{clientid}', 'ClientController@docstoreupload');
Route::get('/client/showdoc/{docid}', 'ClientController@showdoc');
Route::get('/client/showpic/{docid}', 'ClientController@showpic');
Route::get('/client/removedoc/{docid}/{clientid}', 'ClientController@removedoc');
Route::get('/client/check_client', 'ClientController@check_client');
Route::get('/client/api/lookup', 'ClientController@client_lookup');

Route::any('/client/{client}/store-shortlist', 'ClientController@store_shortlist');

/* todo fix controller */
Route::any('/shortlist/manage/{shortlist}', 'ClientController@manage_shortlist_start');
Route::any('/shortlist/manage-end', 'ClientController@manage_shortlist_end');
Route::any('/shortlist/update/{shortlist}', 'ClientController@manage_shortlist_update');
Route::any('/shortlist/show/{shortlist}', 'ClientController@shortlist_index');
Route::any('/shortlist/print/{shortlist}', 'ClientController@shortlist_print');
Route::any('/shortlist/store/{shortlist}', 'ClientShortlistController@store');
Route::any('/shortlist/show-order/{shortlist}', 'ClientShortlistController@show_order');
// Route::any('/shortlist/show-order/{shortlist}', 'ClientController@shortlist_index');
Route::any('/shortlists', 'ClientShortlistController@index');
Route::any('/allshortlists', 'ClientShortlistController@indexall');
Route::get('/shortlists/api/index', 'ClientShortlistController@api_index');
Route::any('/shortlist/option/toggle-type', 'ClientShortlistController@api_toggle_type');
Route::any('/shortlist/option/print', 'ClientShortlistController@option_print');
Route::any('/shortlist/option/printagent', 'ClientShortlistController@option_print_agent');
Route::any('/shortlist/option/delete', 'ClientShortlistController@option_select');
Route::any('/shortlist/option/reorder', 'ClientShortlistController@option_reorder');
Route::any('/shortlist/addtoview/{shortlist}', 'ClientShortlistController@addtoview');
Route::any('/shortlist/addtoview/{shortlist}/{vid}', 'ClientShortlistController@addtoviewid');

Route::any('/viewing/create/{shortlist}', 'ClientViewingController@create');
Route::any('/viewing/store', 'ClientViewingController@store');
Route::any('/viewing/update/{viewing}', 'ClientViewingController@update');
Route::any('/viewing/remove/{viewing}', 'ClientViewingController@remove');
Route::any('/viewing/show/{viewing}', 'ClientViewingController@show');
Route::any('/viewing/show-order/{viewingid}', 'ClientViewingController@show_order');
Route::any('/viewing/option/toggle-type/{viewing}', 'ClientViewingController@api_toggle_type');
Route::any('/viewing/option/print/{viewing}', 'ClientViewingController@option_print');
Route::any('/viewing/option/printagent/{viewing}', 'ClientViewingController@option_print_agent');
Route::any('/viewing/option/delete/{viewing}', 'ClientViewingController@option_remove');
Route::any('/viewing/option/reorder', 'ClientViewingController@option_reorder');

Route::any('/photoshoot/create', 'PhotoshootController@create');
Route::any('/photoshoot/store', 'PhotoshootController@store');
Route::any('/photoshoot/update/{photoshoot}', 'PhotoshootController@update');
Route::any('/photoshoot/remove/{photoshoot}', 'PhotoshootController@remove');
Route::any('/photoshoot/show/{photoshoot}', 'PhotoshootController@show');
Route::any('/photoshoot/show-order/{photoshootid}', 'PhotoshootController@show_order');
Route::any('/photoshoot/option/toggle-type/{photoshoot}', 'PhotoshootController@api_toggle_type');
Route::any('/photoshoot/option/delete/{photoshoot}', 'PhotoshootController@option_remove');
Route::any('/photoshoot/option/reorder', 'PhotoshootController@option_reorder');
Route::any('/photoshoot/addtoshoot/{vid}', 'PhotoshootController@addtoshoot');
Route::any('/photoshoot/main/delete', 'PhotoshootController@main_remove');
Route::any('/photoshoot/option/print', 'PhotoshootController@option_print');
Route::any('/photoshoot/option/printagent', 'PhotoshootController@option_print_agent');


Route::get('/resources', 'ResourceController@index');
Route::get('/resources/pdf/edit', 'ResourceController@editPdfTutorials');
Route::post('/resources/pdf/save', 'ResourceController@savePdfTutorial');
Route::get('/resources/pdf/remove/{id}', 'ResourceController@removePdfTutorial');
Route::get('/resources/{key}/edit', 'ResourceController@editPersonal');
Route::post('/resources/{key}/save', 'ResourceController@saveResource');
Route::any('/pdfresource/{pdf}', 'ResourceController@loadpdf');


Route::get('/home', 'HomeController@index');
//Route::get('/dbtest', 'DbController@index');



//new routes
Route::get('/comments/{id}', 'PropertyController@getcomments');
Route::post('/commentadd/{id}', 'PropertyController@addcomment');
Route::post('/commentremove/{id}', 'PropertyController@removecomment');

Route::get('/list', 'PropertyController@propertylist');
Route::any('/listsearch', 'PropertyController@propertylistsearch');
Route::any('/listadvsearch', 'PropertyController@propertylistadvsearch');

Route::get('/showcontent/{id}', 'PropertyController@getshowcontent');
Route::get('/showinformation/{id}', 'PropertyController@getshowinformation');
Route::get('/showpics/{id}', 'PropertyController@getshowpics');
Route::get('/showpicsoriginal/{id}', 'PropertyController@getshowpicsoriginal');
Route::get('/showcontact/{id}', 'PropertyController@getshowcontact');
Route::get('/showpropertyclients/{id}', 'PropertyController@getpropertyclients');
Route::get('/getpiclinks/{id}', 'PropertyController@getpiclinks');

Route::get('/vendor/comments/{id}', 'VendorController@getcomments');
Route::post('/vendor/commentadd/{id}', 'VendorController@addcomment');
Route::post('/vendor/commentremove/{id}', 'VendorController@removecomment');

Route::get('/property/changes/{id}', 'PropertyController@getchanges');
Route::get('/property/leasesales/{id}', 'PropertyController@getleasesales');

Route::get('/buildings/comments/{id}', 'BuildingController@getcomments');
Route::post('/buildings/commentadd/{id}', 'BuildingController@addcomment');
Route::post('/buildings/commentremove/{id}', 'BuildingController@removecomment');

Route::get('/client/comments/{id}', 'ClientController@getcomments');

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{

	CONST NAOMI_ID = 6;
	CONST WILLIAM_ID = 7;
	const ACTIVE = 0;
	
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone', 'firstname', 'lastname', 'agentid', 'address', 'offtitle', 'picpath', 'gender', 'roles', 'status', 'sigpath', 'commstruct', 'color','allowed_vacation','vacation_tier','remaining_vacation', 'startdate', 'enddate', 'hkid', 'expensifyid', 'managing', 'sales_leaders'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Get all of the properties for the user.
     */
    public function properties()
    {
        return $this->hasMany(Property::class);
    }

    /**
     * Get all of the buildings for the user.
     */
    public function buildings()
    {
        return $this->hasMany(Building::class);
    }

    /**
     * Get all of the vendors for the user.
     */
    public function vendors()
    {
        return $this->hasMany(Vendor::class);
    }

    /**
     * Get all of the vendors for the user.
     */
    public function clients()
    {
        return $this->hasMany(Client::class);
    }

    public function imports()
    {
        return $this->hasMany(Import::class);
    }
	
	
	//Rights management
	public function getEmptyRights(){
		return array(
			'Superadmin' => false,
			'Director' => false,
			'Admin' => false,
			'Accountant' => false,
			'Informationofficer' => false,
			'Consultant' => false,
			'Officemanager' => false,
			'Designer' => false,
			'Photographer' => false,
			'Driver' => false,
			'Salesteamleader' => false
		);
	}
	
	public function getUserRights(){
		if ($this->roles == null || trim($this->roles) == ''){
			$this->roles = json_encode($this->getEmptyRights());
			$this->save();
		}
		
		$rights = json_decode($this->roles, true);
		
		//Admins should be able to see everything except the company section
		if (isset($rights['Admin']) && $rights['Admin']){
			$rights['Superadmin'] = true;
		}else{
			$rights['Admin'] = false;
		}
		
		if ($this->email == 'admin@nest-property.com'){
			$rights['Superadmin'] = true;
		}
		
		return $rights;
	}
	
	public function getUserManaging(){
		if ($this->managing == null || trim($this->managing) == ''){
			$this->managing = json_encode(array());
			$this->save();
		}
		
		$managing = json_decode($this->managing, true);
		
		return $managing;
	}

	public function getSalesLeaders()
	{
		if ($this->sales_leaders == null || trim($this->sales_leaders) == ''){
			$this->sales_leaders = json_encode(array());
			$this->save();
		}
		
		return json_decode($this->sales_leaders, true);
	}
	
	public function setUserRights($rights){
		$this->roles = json_encode($rights);
		$this->save();
	}
	
	public function getUserRightsString(){
		$rights = $this->getUserRights();
		
		$str = '';
		if ($rights['Superadmin'] && !$rights['Admin']){
			if ($str == '') $str = 'Superadmin'; else $str .= ', Superadmin';
		}
		if ($rights['Director']){
			if ($str == '') $str = 'Director'; else $str .= ', Director';
		}
		if ($rights['Admin']){
			if ($str == '') $str = 'Admin'; else $str .= ', Admin';
		}
		if ($rights['Accountant']){
			if ($str == '') $str = 'Accountant'; else $str .= ', Accountant';
		}
		if ($rights['Informationofficer']){
			if ($str == '') $str = 'Information Officer'; else $str .= ', Information Officer';
		}
		if ($rights['Consultant']){
			if ($str == '') $str = 'Consultant'; else $str .= ', Consultant';
		}
		if ($rights['Officemanager']){
			if ($str == '') $str = 'Office Manager'; else $str .= ', Office Manager';
		}
		if (isset($rights['Designer']) && $rights['Designer']){
			if ($str == '') $str = 'Designer'; else $str .= ', UI Designer';
		}
		if (isset($rights['Photographer']) && $rights['Photographer']){
			if ($str == '') $str = 'Photographer'; else $str .= ', Photographer';
		}
		if (isset($rights['Driver']) && $rights['Driver']){
			if ($str == '') $str = 'Driver'; else $str .= ', Driver';
		}
		
		return $str;
	}
	
	public function getUserRightsNameArr(){
		$ret = array(
			'Superadmin' => 'Superadmin',
			'Director' => 'Director',
			'Admin' => 'Admin',
			'Accountant' => 'Accountant',
			'Informationofficer' => 'Information Officer',
			'Consultant' => 'Consultant',
			'Officemanager' => 'Office Manager',
			'Designer' => 'UI Designer',
			'Photographer' => 'Photographer',
			'Driver' => 'Driver',
			'Salesteamleader' => 'Sales Team Leader'
		);
		
		return $ret;
	}
	
	public function isConsultant(){
		$rights = $this->getUserRights();
		
		if (isset($rights['Consultant']) && $rights['Consultant']){
			return true;
		}else{
			return false;
		}
	}
	
	public function isOfficeManager(){
		$rights = $this->getUserRights();
		
		if (isset($rights['Officemanager']) && $rights['Officemanager']){
			return true;
		}else{
			return false;
		}
	}
	
	public function isInformationofficer(){
		$rights = $this->getUserRights();
		
		if (isset($rights['Informationofficer']) && $rights['Informationofficer']){
			return true;
		}else{
			return false;
		}
	}
	
	public function isOnlyDriver(){
		$rights = $this->getUserRights();
		
		$count = 0;
		foreach ($rights as $x){
			if ($x){
				$count++;
			}
		}
		
		if (isset($rights['Driver']) && $rights['Driver'] && $count == 1){
			return true;
		}else{
			return false;
		}
	}
	
	public function isOnlyPhotographer(){
		$rights = $this->getUserRights();
		
		$count = 0;
		foreach ($rights as $x){
			if ($x){
				$count++;
			}
		}
		
		if (isset($rights['Photographer']) && $rights['Photographer'] && $count == 1){
			return true;
		}else{
			return false;
		}
	}
	
	

	public function property_deleted_by()
    {
        return $this->belongsTo('App\PropertyDeleteLogs', 'deleted_by');
    }
	public function property_deleted_confirmed_by()
    {
        return $this->belongsTo('App\PropertyDeleteLogs', 'confirmed_by');
    }

	public function getIsManagementAttribute(){
		return $this->getUserRights()['Superadmin'] || $this->getUserRights()['Admin'] || $this->getUserRights()['Director'];
	}
	
	
}

resources/views/clients/index.blade.php
	@extends('layouts.app')

@section('content')

            <!-- Client Search -->
            <div class="nest-buildings-search-panel panel panel-default">
                <div class="panel-body">
                    <!-- New Property Form -->
                    <form action="{{ url('clients') }}" method="GET" class="form-horizontal">
                        <div class="nest-buildings-search-wrapper row">
                            <div class="col-sm-4">
                                <input type="text" name="sstring" placeholder="First name, last name, workplace, email, etc." class="form-control" value="{{ old('name', $input->name) }}">
                            </div>
                            <div class="col-sm-4">
                                <input type="text" name="tel" placeholder="Phone number" id="client-tel" class="form-control" value="{{ old('tel', $input->tel) }}">
                            </div> 
                            <div class="col-sm-4">
                                <input type="text" name="id" placeholder="Client ID" id="client-id" class="form-control" value="{{ old('id', $input->id) }}">
                            </div>
							<div class="clearfix"></div>
                        </div>
                        <div class="nest-buildings-search-wrapper row">
                            <div class="col-sm-4">
                                <input type="number" name="budget_min" placeholder="Budget (Min)" id="client-budget_min" class="form-control" value="{{ old('budget_min', $input->budget_min) }}">
                            </div>
                            <div class="col-sm-4">
                                <input type="number" name="budget_max" placeholder="Budget (Max)" id="client-budget_max" class="form-control" value="{{ old('budget_max', $input->budget_max) }}">
                            </div>
                            @if(Auth::user()->is_management)
                            <div class="col-sm-4">
                                <select id="consultant" name="user_id" class="form-control">
                                    <option value="">All Consultants</option>
                                    @foreach ($consultants as $c)
                                        <option {{(isset($input->user_id)  && $input->user_id == $c->id) ? 'selected': ''}} value="{{$c->id}}">{{$c->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            @endif
							<input type="hidden" name="tempature" value="" />
							<!--
                            <div class="col-sm-4">
                                <select class="form-control" name="tempature">
									<option value="">Choose a temperature</option>
									<option value="Cold">Cold</option>
									<option value="Warm">Warm</option>
									<option value="Hot">Hot</option>
								</select>
                            </div>
							-->
							<div class="clearfix"></div>
                        </div>
                        @if(Auth::user()->is_management)
						<div class="nest-buildings-search-wrapper row">
                            <div class="col-sm-4">
                                <select id="sort" name="sort" class="form-control">
                                    <option value="">Order by ID (High to Low)</option>
                                    <option {{(isset($input->sort)  && $input->sort == 'id_asc') ? 'selected': ''}} value="id_asc">Order by ID (Low to High)</option>
                                    <option {{(isset($input->sort)  && $input->sort == 'consultant_asc') ? 'selected': ''}} value="consultant_asc">Order by Consultant's Name (A-Z)</option>
                                    <option {{(isset($input->sort)  && $input->sort == 'consultant_desc') ? 'selected': ''}} value="consultant_desc">Order by Consultant's Name (Z-A)</option>
                                </select>
                            </div>
                        </div>
                        @endif
                        <!-- <div class="form-group">
                            <div class="col-sm-4">
                                <label for="client-firstname" class="control-label">First Name</label>
                                <input type="text" name="firstname" id="client-firstname" class="form-control" value="{{ old('firstname', $input->firstname) }}" >
                            </div>
                            <div class="col-sm-4">
                                <label for="client-lastname" class="control-label">Last Name</label>
                                <input type="text" name="lastname" id="client-lastname" class="form-control" value="{{ old('lastname', $input->lastname) }}" >
                            </div>
                            <div class="col-sm-4">
                                <label for="client-tel" class="control-label">Tel</label>
                                <input type="number" name="tel" id="client-tel" class="form-control" value="{{ old('tel', $input->tel) }}">
                            </div> 
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4">
                                <label for="client-email" class="control-label">Email</label>
                                <input type="text" name="email" id="client-email" class="form-control" value="{{ old('email', $input->email) }}">  
                            </div>
                            <div class="col-sm-4">
                                <label for="client-workplace" class="control-label">Workplace</label>
                                <input type="text" name="workplace" id="client-workplace" class="form-control" value="{{ old('workplace', $input->workplace) }}">
                            </div>
                            <div class="col-sm-4">
                                <label for="client-title" class="control-label">Title</label>
                                <input type="text" name="title" id="client-title" class="form-control" value="{{ old('title', $input->title) }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4">
                                <label for="client-budget_min" class="control-label">Budget (Min)</label>
                                <input type="number" name="budget_min" id="client-budget_min" class="form-control" value="{{ old('budget_min', $input->budget_min) }}">
                            </div>
                            <div class="col-sm-4">
                                <label for="client-budget_max" class="control-label">Budget (Max)</label>
                                <input type="number" name="budget_max" id="client-budget_max" class="form-control" value="{{ old('budget_max', $input->budget_max) }}">
                            </div>
                            <div class="col-sm-4">
                                <label for="client-id" class="control-label">ID</label>
                                <input type="text" name="id" id="client-id" class="form-control" value="{{ old('id', $input->id) }}">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-4">
                                <label for="client-tempature" class="control-label">Tempature</label>
                                <div style="display: block;">
                                    <label for="client-tempature-0" class="control-label">{!! Form::radio('tempature', '', $input->tempature=='', ['id'=>'client-tempature-0']) !!} Any</label>
                                    <label for="client-tempature-1" class="control-label">{!! Form::radio('tempature', 'Cold', $input->tempature=='Cold', ['id'=>'client-tempature-1']) !!} Cold</label>
                                    <label for="client-tempature-2" class="control-label">{!! Form::radio('tempature', 'Warm', $input->tempature=='Warm', ['id'=>'client-tempature-2']) !!} Warm</label>
                                    <label for="client-tempature-3" class="control-label">{!! Form::radio('tempature', 'Hot', $input->tempature=='Hot', ['id'=>'client-tempature-3']) !!} Hot</label>
                                </div>
                            </div>
                        </div>-->
						
						<div class="nest-buildings-search-buttons-wrapper row">
							<div class="col-xs-6">
								<a class="nest-button btn btn-primary" href="{{ url('client/create') }}">
									<i class="fa fa-btn fa-plus"></i>Add Client
								</a>
							</div>
                            <div class="col-xs-6">
                                <button type="submit" name="action" value="search" class="nest-button nest-right-button btn btn-default">
                                    <i class="fa fa-btn fa-search"></i>Search </button>
                            </div>
						</div>
                    </form>
					<div style="padding-top:15px;text-align:right;">
						@if (Auth::user()->getUserRights()['Superadmin'] || Auth::user()->getUserRights()['Director'])
							To search for "Ultra High Net Worth" clients, please type "uhnw" into the "Client ID" field and click "Search"
						@endif
					</div>
                </div>
            </div>

            <!-- Current Clients -->
            @if (count($clients) > 0)
				<div>
					<div class="nest-buildings-result-wrapper">
						@foreach ($clients as $index => $client)
							<div class="row 
							@if ($index%2 == 1)
								nest-striped
							@endif
							">
								<div class="col-lg-3 col-md-3 col-sm-6">
									<b>Client:</b> <a href="{{ url('client/show/'.$client->id) }}">{{ $client->name() }} 
										@if( !empty($client->description()))
											(<i>{{ $client->description() }}</i>) 
										@endif
										@if( !empty($client->name2()) )
											/ {{ $client->name2() }} 
										@endif
										@if( !empty($client->description2()))
											(<i>{{ $client->description2() }}</i>)
										@endif</a><br />
									<b>ID:</b> {{ $client->id }}
								</div>
								<div class="col-lg-3 col-md-3 col-sm-6">
									<b>Tel:</b> {!! $client->telLinked() !!} 
										@if( !empty($client->tel2) )
											/ {!! $client->tel2Linked() !!}
										@endif<br />
									<b>Email:</b> {{ $client->email() }} 
										@if( !empty($client->email2) )
											/ {{ $client->email2() }}
										@endif<br />
									<b>Budget:</b> {{ $client->budget() }}
								</div>
								<div class="col-lg-3 col-md-3 col-sm-6">
									<b>Consultant:</b> {{ $client->user->name }}<br />
									<b>Shortlist:</b> {{ $client->shortlists()->count() }}
								</div>
								<div class="col-lg-3 col-md-3 col-sm-6">
									<a class="nest-button nest-right-button btn btn-primary" href="{{ url('client/edit/'.$client->id) }}">
										<i class="fa fa-btn fa-pencil-square-o"></i>Edit
									</a>
									<a class="nest-button nest-right-button btn btn-primary" href="{{ url('client/show/'.$client->id) }}">
										<i class="fa fa-btn fa-info-circle"></i>View
									</a>
								</div>
								<div class="clearfix"></div>
							</div>
						@endforeach
					</div>
					@if ($clients->lastPage() > 1)
						<div class="panel-footer nest-buildings-pagination">
							<!-- <div style="margin: 10px 0;">Page {{ $clients->currentPage() }} of {{ $clients->lastPage() }} (Total: {{ $clients->total() }} items)</div> -->
							{{ $clients->links() }}
						</div>
					@endif
				</div>
            @endif
		<script>
			jQuery('form').on('focus', 'input[type=number]', function (e) {
				jQuery(this).on('mousewheel.disableScroll', function (e) {
					e.preventDefault();
				});
			});
			jQuery('form').on('blur', 'input[type=number]', function (e) {
				jQuery(this).off('mousewheel.disableScroll');
			});
		</script>
@endsection